Update Dockerfile-WinTenCermin-megasdkrest

diff --git a/Dockerfile-WinTenCermin-megasdkrest b/Dockerfile-WinTenCermin-megasdkrest
--- a/Dockerfile-WinTenCermin-megasdkrest
+++ b/Dockerfile-WinTenCermin-megasdkrest
@@ -1,18 +1,35 @@
 FROM ubuntu:20.04
 
-WORKDIR /usr/src/app
+RUN set -ex \
+    # Setup environment
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -qq update \
+    && apt-get -qq -y dist-upgrade \
+    && apt-get -qq -y install --no-install-recommends \
+        locales python3 python3-lxml python3-pip \
+        # MegaSDK-REST dependencies
+        libc-ares-dev libcrypto++-dev libcurl4-openssl-dev \
+        libmagic-dev libsodium-dev libsqlite3-dev libssl-dev \
+        # MirrorBot dependencies
+        aria2 curl ffmpeg jq p7zip-full p7zip-rar pv \
+    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
+    && locale-gen \
+    # Setup MirrorBot dependencies
+    && curl -fsSL https://github.com/jaskaranSM/megasdkrest/releases/download/v0.1/megasdkrest -o /usr/local/bin/megasdkrest \
+    && chmod +x /usr/local/bin/megasdkrest \
+    && curl -fsSLO https://raw.githubusercontent.com/jovanzers/WinTenCerminInsider/bot5-megarest/requirements.txt?token=GHSAT0AAAAAABRRAKME66FFALWCP3IVURWKYQZ56FQ \
+    && pip3 install --no-cache-dir -r requirements.txt \
+    && rm requirements.txt \
+    # Cleanup environment
+    && apt-get -qq -y autoremove --purge \
+    && apt-get -qq -y clean \
+    && rm -rf -- /var/lib/apt/lists/* /var/cache/apt/archives/* /etc/apt/sources.list.d/*
 
-RUN apt-get -qq update && \
-    DEBIAN_FRONTEND="noninteractive" apt-get -qq install -y tzdata aria2 python3 python3-pip \
-    locales python3-lxml \
-    curl pv jq ffmpeg \
-    p7zip-full p7zip-rar \
-    libcrypto++-dev libssl-dev \
-    libc-ares-dev libcurl4-openssl-dev \
-    libsqlite3-dev libsodium-dev
+ENV DEBIAN_FRONTEND=noninteractive \
+    LANG=en_US.UTF-8 \
+    LANGUAGE=en_US:en \
+    LC_ALL=en_US.UTF-8
 
-ENV TZ Asia/Jakarta
-RUN locale-gen en_US.UTF-8
-ENV LANG en_US.UTF-8
-ENV LANGUAGE en_US:en
-ENV LC_ALL en_US.UTF-8
+CMD ["bash", "start.sh"]
+
+# vim: ft=dockerfile
