Update Dockerfile-WinTenCermin

diff --git a/Dockerfile-WinTenCermin b/Dockerfile-WinTenCermin
--- a/Dockerfile-WinTenCermin
+++ b/Dockerfile-WinTenCermin
@@ -1,36 +1,47 @@
-FROM python:3.9.0-slim-buster
+FROM python:3-slim-buster
 
-ENV DEBIAN_FRONTEND=noninteractive
-
-RUN apt-get -qq update \
-    && apt-get -qq install -y --no-install-recommends \
-        git g++ gcc autoconf automake \
-        m4 libtool qt4-qmake make libqt4-dev libcurl4-openssl-dev \
-        libcrypto++-dev libsqlite3-dev libc-ares-dev \
-        libsodium-dev libnautilus-extension-dev \
-        libssl-dev libfreeimage-dev swig \
-    && apt-get -y autoremove
-    
-# Installing mega sdk python binding
-ENV MEGA_SDK_VERSION '3.9.0'
-RUN git clone https://github.com/meganz/sdk.git sdk && cd sdk \
-    && git checkout v$MEGA_SDK_VERSION \
-    && ./autogen.sh && ./configure --disable-silent-rules --enable-python --with-sodium --disable-examples \
+RUN set -ex \
+    # setup env
+    && export DEBIAN_FRONTEND=noninteractive \
+    && apt-get -qq update \
+    && apt-get -qq -y install software-properties-common \
+    && apt-add-repository non-free \
+    && apt-get -qq update \
+    && apt-get -qq -y install --no-install-recommends \
+        # build deps
+        autoconf automake g++ gcc git libtool m4 make swig \
+        # mega sdk deps
+        libc-ares-dev libcrypto++-dev libcurl4-openssl-dev \
+        libfreeimage-dev libsodium-dev libsqlite3-dev libssl-dev zlib1g-dev \
+        # mirror bot deps
+        aria2 curl ffmpeg jq locales p7zip-full p7zip-rar pv python3-lxml \
+    && apt-get -qq -y autoremove --purge \
+    && sed -i '/en_US.UTF-8/s/^# //g' /etc/locale.gen \
+    && locale-gen \
+    # setup mega sdk
+    && MEGA_SDK_VERSION="3.8.6" \
+    && git clone https://github.com/meganz/sdk.git --depth=1 -b v$MEGA_SDK_VERSION ~/sdk \
+    && cd ~/sdk \
+    && rm -rf .git \
+    && ./autogen.sh \
+    && ./configure --disable-silent-rules --enable-python --with-sodium --disable-examples \
     && make -j$(nproc --all) \
-    && cd bindings/python/ && python3 setup.py bdist_wheel \
-    && cd dist/ && pip3 install --no-cache-dir megasdk-$MEGA_SDK_VERSION-*.whl
-    
-RUN apt-get -qq update && \
-    apt-get install -y software-properties-common && \
-    rm -rf /var/lib/apt/lists/* && \
-    apt-add-repository non-free && \
-    apt-get -qq update && \
-    apt-get -qq install -y p7zip-full p7zip-rar unzip wget aria2 curl pv jq ffmpeg locales python3-lxml && \
-    apt-get purge -y software-properties-common
-    
-RUN pip3 install --no-cache-dir -r requirements.txt
-ENV TZ Asia/Jakarta
-RUN sed -i -e 's/# id_ID.UTF-8 UTF-8/id_ID.UTF-8 UTF-8/' /etc/locale.gen && locale-gen
-ENV LANG id_ID.UTF-8
-ENV LANGUAGE id_ID:id
-ENV LC_ALL id_ID.UTF-8
+    && cd bindings/python/ \
+    && python3 setup.py bdist_wheel \
+    && cd dist/ \
+    && pip3 install --no-cache-dir megasdk-$MEGA_SDK_VERSION-*.whl \
+    && cd ~ \
+    # setup mirror bot python deps
+    && curl -fsSLO https://raw.githubusercontent.com/KenHV/Mirror-Bot/master/requirements.txt \
+    && pip3 install --no-cache-dir -r requirements.txt \
+    && rm requirements.txt \
+    # cleanup env
+    && apt-get -qq -y purge --autoremove \
+        autoconf automake g++ gcc git libtool m4 make software-properties-common swig \
+    && apt-get -qq -y clean \
+    && rm -rf -- /var/lib/apt/lists/* /var/cache/apt/archives/* /etc/apt/sources.list.d/*
+
+ENV DEBIAN_FRONTEND=noninteractive \
+    LANG=en_US.UTF-8 \
+    LANGUAGE=en_US:en \
+    LC_ALL=en_US.UTF-8
